=== KopterBuzz/NOMNOM/ValidationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["name", "authors", "dependencies", "artifacts"],
  "properties": {
    "name": { "type": "string" },
    "description": { "type": "string" },
    "infoUrl": { "type": "string", "format": "uri" },
    "supportedVersion": { "type": "string" },
    "authors": {
      "type": "array",
      "items": { "type": "string" }
    },
    "dependencies": {
      "type": "array",
      "items": {}
    },
    "artifacts": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["fileName", "version", "artifactUrl"],
        "properties": {
          "fileName": { "type": "string" },
          "version": { "type": "string" },
          "artifactUrl": { "type": "string", "format": "uri" },
          "hash": { "type": "string" },
          "extends": {
            "type": "array",
            "items": {}
          }
        }
      }
    }
  }
}

=== KopterBuzz/NOMNOM/modManifests/NOFakeMod.json
{
    "name":  "NOFakeMod_1",
    "description":  "FakeMod_1 for Testing",
    "infoUrl":  "https://github.com/KopterBuzz/NOFakeMod_1",
    "supportedVersion" : "0.32",
    "authors": ["KopterBuzz"],
    "dependencies" :
    [
                {
                    "name" : "NOBlackBox",
                    "minimumVersion" : "0.3.8.2"
                }  
    ],
    "artifacts" :
    [
        {
            "fileName" : "NOFakeMod_1-1.0.0.0.zip",        
            "version":  "0.3.8.2",
            "artifactUrl":  "https://github.com/KopterBuzz/NOFakeMod_1/releases/download/1.0.0.0/NOBlackBox-1.0.0.0.zip",
            "hash": "sha256:4a1b37d5b3cde5ac5b53b86ef85d7c9ad3fe1b88935021cf18eb62f99c69d6bf",
            "extends" :
            [
                {
                    "name" : "NOBlackBox",
                    "minimumVersion" : "0.3.8.2"
                }            
            ]
        }
    ]
}
